export const projects = [
   {
      background: "/static/assets/images/dragon-site.jpg",
      color: "00c086",
      fillImage: "andromedaFour",
      identifier: "dragon",
      image: "/static/assets/images/cloud.png",
      linkto: "/dragon-writer",
      lineOne: "Node, Express,",
      lineTwo: "React, & MongoDB",
      offset: "20",
      offsetX1: "92",
      offsetX2: "76",
      offsetY: "356",
      title: "DRAGON WRITER"
   },
   {
      background: "/static/assets/images/vandelay-site.jpg",
      color: "582aff",
      fillImage: "andromeda",
      identifier: "vandelay",
      image: "/static/assets/images/vandelay.png",
      linkto: "https://vandelay-rentals.herokuapp.com/",
      lineOne: "Node, Express,",
      lineTwo: "React, & MongoDB",
      offset: "14.5",
      offsetX1: "92",
      offsetX2: "76",
      offsetY: "356",
      title: "VANDELAY RENTALS"
   },
   {
      background: "/static/assets/images/money-site.jpg",
      color: "009921",
      fillImage: "andromedaTwo",
      identifier: "money",
      image: "/static/assets/images/skull.png",
      linkto: "https://mind-over-money.herokuapp.com/",
      lineOne: "Node, Express,",
      lineTwo: "React, & MySQL",
      offset: "17",
      offsetX1: "94",
      offsetX2: "89",
      offsetY: "356",
      title: "MIND OVER MONEY"
   },
   {
      background: "/static/assets/images/eventvaark-site.jpg",
      color: "850000",
      fillImage: "andromedaThree",
      identifier: "eventvaark",
      image: "/static/assets/images/aardvark.png",
      linkto: "https://strangebrewer.github.io/01-Event-Vaark/",
      lineOne: "JQuery & Firebase",
      lineTwo: "",
      offset: "26",
      offsetX1: "78",
      offsetX2: "",
      offsetY: "364",
      title: "EVENT VAARK"
   },
   {
      background: "/static/assets/images/liri-site.jpg",
      color: "00eef7",
      fillImage: "andromedaFive",
      identifier: "liri",
      image: "/static/assets/images/kallisti.png",
      linkto: "https://github.com/Strangebrewer/01-liri-node-app",
      lineOne: "JavaScript & Node",
      lineTwo: "",
      offset: "34",
      offsetX1: "78",
      offsetX2: "",
      offsetY: "364",
      title: "ASK LIRI"
   },
   {
      fillImage: "starwars",
      identifier: "starwars",
      image: "",
      linkto: "",
      offset: "20",
      lineOne: "Bad Intentions",
      lineTwo: "",
      offsetX1: "88",
      offsetX2: "",
      offsetY: "364",
      title: "THAT'S NO MOON"
   }
]